
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Box } from "@chakra-ui/react";
import Header from "../components/header/Header";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>WebMentor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Header />

        <Box paddingX={"12"} mt={"12"}>
          hi welcome to my portfolio
        </Box>
        <Box mt={"8"} pb={"4"} paddingX={"12"}>
          <Footer />
        </Box>
      </Box>
    </div>
  );
}
