import fs from "fs";
import path from "path";
import matter from "gray-matter";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Box, SimpleGrid } from "@chakra-ui/react";
import Header from "../components/header/Header";
import Search from "../components/Search";
import PostCard from "../components/PostCard";
import { sortByDate } from "../Helpers";
import Category from "../components/Category";

export default function Home({ posts }) {
  console.log(posts);
  return (
    <div className={styles.container}>
      <Head>
        <title>WebMentor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Header />
        <Search />
        <Category />
        <Box paddingX={"12"} mt={"12"}>
          <SimpleGrid columns={3} spacing={6}>
            {posts.map((post) => (
              <PostCard
                title={post.postData.title}
                date={post.postData.date}
                author={post.postData.author}
                coverImg={post.postData.cover_image}
                category={post.postData.category}
                excerpt={post.postData.excerpt}
                slug={post.slug}
              />
            ))}
          </SimpleGrid>
        </Box>
      </Box>
    </div>
  );
}

export async function getStaticProps() {
  const files = fs.readdirSync(path.join("posts"));
  const posts = files.map((post) => {
    const slug = post.replace(".md", "");
    const markdownWithMatter = fs.readFileSync(
      path.join("posts", post),
      "utf-8"
    );
    const { data: postData } = matter(markdownWithMatter);
    return {
      slug,
      postData,
    };
  });
  return {
    props: {
      posts: posts.sort(sortByDate).slice(0, 6)
    },
  };
}
